name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Promenite na 8.2 da se poklapa sa vašim lokalnim okruženjem
          extensions: mbstring, bcmath, xml

      - name: Check PHP Version  # Dodato ovde
        run: php -v

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --prefer-dist --no-interaction

      - name: Run tests
        run: php artisan test
