name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml

      - name: Instalacija Composer paketa
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --prefer-dist --no-interaction

      - name: Kreiranje .env fajla
        run: cp .env.example .env

      - name: Generisanje APP_KEY
        run: php artisan key:generate

      - name: Pokretanje testova
        run: php artisan test
